export interface Match {
  id: string;
  homeTeam: string;
  awayTeam: string;
  homeLogo: string;
  awayLogo: string;
  homeScore: number | null;
  awayScore: number | null;
  status: 'scheduled' | 'live' | 'finished';
  date: string; // ISO string or simple date string
  league: string;
}

export interface Gameweek {
  id: string;
  title: string; // e.g., "الجولة الأولى" (Gameweek 1)
  status: 'upcoming' | 'live' | 'completed';
  matches: Match[];
  aiCommentary?: string; // Sarcastic commentary generated by Gemini
}

export interface User {
  id: string;
  name: string;
  isYouTuber: boolean;
  avatarUrl: string;
  totalPoints: number;
  exactScoresCount: number;
  correctOutcomesCount: number;
  favoriteTeam?: string;
}

export interface Prediction {
  id: string;
  userId: string;
  matchId: string;
  predictedHomeScore: number;
  predictedAwayScore: number;
  pointsEarned?: number | null;
  calculated?: boolean;
}

export interface DbState {
  users: User[];
  gameweeks: Gameweek[];
  predictions: Prediction[];
}
